spring:
  application:
    name: projection-service
  datasource:
    url: ${PROJECTION_DB_URL:jdbc:postgresql://localhost:5432/projection_svc}
    username: ${PROJECTION_DB_USER:projection_svc}
    password: ${PROJECTION_DB_PASSWORD:projection_svc}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: projection-service
      properties:
        isolation.level: read_committed
      auto-offset-reset: earliest

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
